### ISSUE TITLE
Introduce Project.toml

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/Games.jl#119]
I have no idea how.
@shizejin Do you?

**Comment by shizejin** [comment]
@oyamad Does [this](https://stackoverflow.com/questions/55312893/about-project-toml) looks like a correct way to generate `Project.toml` properly? If you would think so, I can try to work on this.

**Comment by oyamad** [comment]
@shizejin And maybe [this](https://github.com/JuliaRegistries/Registrator.jl#transitioning-from-require-to-projecttoml)? Can you make a try, thanks!
