### ISSUE TITLE
codecov with GitHub Actions

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/Games.jl#135]
Results from `codecov` are not reported.
Do we need to install [Codecov GitHub App](https://github.com/apps/codecov) to the QuantEcon organization?

**Comment by thomasrockhu** [comment]
Tom from Codecov here. @oyamad, I see results [here](https://app.codecov.io/gh/QuantEcon/Games.jl/commits?page=1), are there missing commits or that results aren't posted back to PRs?

If that is the problem, I would highly recommend installing the app.

**Comment by oyamad** [comment]
@thomasrockhu Thanks for your reply.

If you go to, e.g., this page https://github.com/QuantEcon/Games.jl/commit/8f39f3356b92c374b4c0e7aa03cf90e393a2a218 and click the red cross mark in front of "Merge pull request #134 from QuantEcon/ci-nightly", you will see a list of "CI-nightly ...", "CI ...", etc, but no codecov report is there.

Compare this page https://github.com/oyamad/MatchingMarkets.jl/commit/37b146993e96db0bdf1c62a251fd8fd1d1c24e0c, where there are `codecov/patch ...` and `codecov/project ...` entries in the list which shows up by clicking the check mark in front of "Fix badge".

One difference is that the former belongs to the QuantEcon organization, whereas the latter is my own repo. (I never installed Codecov app to my account, though.)

**Comment by thomasrockhu** [comment]
Taking a quick look at the first commit, I would really recommend installing the app. We have seen intermittent behavior with users who do not use it and us being able to communicate with GitHub on behalf of the user. Having the app helps us to prevent these issues.

**Comment by oyamad** [comment]
App installed, but the situation does not change https://github.com/QuantEcon/Games.jl/commit/9fb6a8c4af940e15ccb6b3eeb4bce2209d07af6c.

**Comment by thomasrockhu** [comment]
@oyamad it looks like the integration was installed, but not for that repository

**Comment by oyamad** [comment]
@thomasrockhu Thanks for the information, but in the settings page, if I click `Click here to see your installation listings.`, then I get `Page not found`...

**Comment by thomasrockhu** [comment]
@oyamad interesting... would you be able to uninstall and re-install the app? I wonder if something weird happened during creation as the link should go to a GitHub hosted page.

**Comment by oyamad** [comment]
@thomasrockhu Thanks, I will try that probably tomorrow.

I found this issue ionelmc/python-hunter#86 which seems reporting the same issue.

**Comment by oyamad** [comment]
@thomasrockhu App uninstalled and then re-installed, and it now succeeded: coverage is report in PR #136 and codecov entries appear in the list https://github.com/QuantEcon/Games.jl/commit/8fc251818a079d802eb034722c25ef0a814d4efd. Thanks!
