### ISSUE TITLE
Repeated Games

### ISSUE THREAD

**Issue by cc7768** [QuantEcon/Games.jl#14]
Thoughts on whether repeated games belong in this repository or a separate one? I have some code (still WIP -- but works) that could solve some 2 player repeated games that I would be willing to add.

Ping: @spencerlyon2 @oyamad @jstac

**Comment by spencerlyon2** [comment]
I vote here as they are still games and the repeated games code might reuse tools here for the stage game.

**Comment by oyamad** [comment]
Vote for it to belong to this repo.

**Comment by cc7768** [comment]
Great. I'll work on writing some docs and send a PR sometime in the future.
