### ISSUE TITLE
Type instability: 1-player game, symmetric 2-player game

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/Games.jl#28]
The problem causing https://github.com/QuantEcon/Games.jl/issues/2#issuecomment-197400877:

* If an M-dimensional array is passed with M>=3, then [`NormalFormGame{T<:Real,M}(payoffs::Array{T,M})`](https://github.com/QuantEcon/Games.jl/blob/master/src/normal_form_game.jl#L453) is called, which returns a `NormalFormGame` with N=M-1>=2 players.

* If a 2-dimensitonal array (matrix) is passed, then [`NormalFormGame{T<:Real}(payoffs::Matrix{T})`](https://github.com/QuantEcon/Games.jl/blob/master/src/normal_form_game.jl#L482) is called and it returns
  - a 1-player `NormalFormGame` if the input array is n x 1;
  - a 2-player `NormalFormGame` if the input array is n x m with m>=2 and is square (n=m), in which case the game is thought of as a symmetric 2-player game.

The latter design is the source of the type instability.

My proposal is:

* let `NormalFormGame{T<:Real}(payoffs::Matrix{T})` always return a 2-player `NormalFormGame` (if `payoff` is square), so that a 1-player game cannot be constructed by a payoff array (vector in this case) and must be constructed by `NormalFormGame(player_with_no_opponent)`, where `player_with_no_opponent` is of type `Player{1,T}`.

**Comment by oyamad** [comment]
Alternative is #5, with removing `NormalFormGame{T<:Real}(payoffs::Matrix{T})`.

**Comment by sglyon** [comment]
I think I like your proposal in the comment at the end of the original post here.

But, I will totally defer to your judgement here.

**Comment by cc7768** [comment]
Hi @oyamad. I think this is a very sensible proposal and a nice solution to the problem.
