### ISSUE TITLE
Add SSH Deploy Keys

### ISSUE THREAD

**Issue by shizejin** [QuantEcon/Games.jl#31]
@sglyon 

Would you please [add the SSH Deploy Keys](https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html#SSH-Deploy-Keys-1) for generating documentation?

The test problem of NormalFromGame has been done.

**Comment by sglyon** [comment]
I think it is done.

**Comment by shizejin** [comment]
It is strange that Travis is not deploying anything in the `gh-pages` branch. If I pull `master` branch of QuantEcon/Games.jl to my forked repo and change [this line](https://github.com/QuantEcon/Games.jl/blob/master/docs/make.jl#L13) to my own repo, the documentation can be generated.

As I have no access to the setting page of QuantEcon/Games.jl, would you mind checking that the key of Documenter has the permission of "Read/write"? Thanks!

**Comment by sglyon** [comment]
I believe that it does...

![screen shot 2017-03-29 at 11 57 07 am](https://cloud.githubusercontent.com/assets/1001948/24464114/e20f84d4-1476-11e7-8eda-f5c11b5b0e98.png)

**Comment by shizejin** [comment]
Thanks! It does have the permission... I will see what is wrong here.

**Comment by oyamad** [comment]
It seems the docs are deployed only when pushed to master.
Anyway they have been deployed: http://quantecon.github.io/Games.jl/latest/

**Comment by shizejin** [comment]
Thanks so much!
