### ISSUE TITLE
Type inference with `Cournot{N}` no longer works in v0.6

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/Games.jl#51]
Cell `[20]` in the [notebook](http://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/1f74eb51f473765079c8c5a417e0e5d94cd032e2/game_theory_jl.ipynb#More-than-two-players).

I found the advice from @StefanKarpinski https://github.com/QuantEcon/Games.jl/issues/2#issuecomment-197579461 does not work for type inference in v0.6:

```jl
using Games

struct Cournot{N} end

function (::Type{Cournot{N}}){N,T<:Real}(a::Real, c::Real, q_grid::Vector{T})
    nums_actions = tuple([length(q_grid) for i in 1:N]...)::NTuple{N,Int}
    S = promote_type(typeof(a), typeof(c), T)
    payoff_array= Array{T}(nums_actions)
    for I in CartesianRange(nums_actions)
        Q = zero(S)
        for i in 1:N
            Q += q_grid[I[i]]::T
        end
        payoff_array[I] = (a - c - Q) * q_grid[I[1]]
    end
    players = tuple([Player(payoff_array) for i in 1:N]...)::NTuple{N,Player{N,T}}
    return NormalFormGame(players)
end

cournot{T<:Real}(a::Real, c::Real, N::Integer, q_grid::Vector{T}) =
    Cournot{N}(a, c, q_grid)


a, c = 80, 20
N = 3
q_grid = [10, 15]

@code_warntype cournot(a, c, N, q_grid)
```

```
Variables:
  #self#::#cournot
  a::Int64
  c::Int64
  N::Int64
  q_grid::Array{Int64,1}

Body:
  begin 
      return ((Core.apply_type)(Main.Cournot, N::Int64)::Type{Cournot{_}} where _)(a::Int64, c::Int64, q_grid::Array{Int64,1})::Games.NormalFormGame{_,_} where _ where _
  end::Games.NormalFormGame{_,_} where _ where _
```

**Comment by oyamad** [comment]
The following works (although there are some `Any`s):

```jl
function cournot(a::Real, c::Real, q_grid::Vector{T}, ::Val{N}) where {N,T <:Real}
    nums_actions = ntuple(x->length(q_grid), Val(N))
    S = promote_type(typeof(a), typeof(c), T)
    payoff_array= Array{S}(nums_actions)
    for I in CartesianRange(nums_actions)
        Q = zero(S)
        for i in 1:length(I)
            Q += q_grid[I[i]]
        end
        payoff_array[I] = (a - c - Q) * q_grid[I[1]]
    end
    players = ntuple(x->Player(payoff_array), Val(N))
    return NormalFormGame(players)
end
```

```jl
a, c = 80, 20
N = 3
q_grid = [10, 15]

@code_warntype cournot(a, c, q_grid, Val(N))
```

```
Variables:
  #self#::#cournot
  a::Int64
  c::Int64
  q_grid::Array{Int64,1}
  #unused#::Val{3}
  i::Int64
  #temp#@_7::Int64
  I::CartesianIndex{3}
  Q::Int64
  #temp#@_10::CartesianIndex{3}
  #1::Any
  #2::Any
  nums_actions::Tuple{Int64,Int64,Int64}
  S::Any
  payoff_array::Array{Int64,3}
  players::Tuple{Games.Player{3,Int64},Games.Player{3,Int64},Games.Player{3,Int64}}
  #3::Base.IteratorsMD.##3#4
  #5::Base.IteratorsMD.##5#6{Int64}
  #temp#@_19::CartesianIndex{3}
  newtail@_20::Tuple{Int64,Int64}
  newtail@_21::Tuple{Int64}
  #temp#@_22::Tuple{Int64,Int64}
  #temp#@_23::Tuple{Int64,Int64,Int64}

Body:
  begin 
      NewvarNode(:(#2::Any))
      NewvarNode(:(players::Tuple{Games.Player{3,Int64},Games.Player{3,Int64},Games.Player{3,Int64}}))
      SSAValue(53) = q_grid::Array{Int64,1}

...

      return $(Expr(:invoke, MethodInstance for Games.NormalFormGame(::Tuple{Games.Player{3,Int64},Games.Player{3,Int64},Games.Player{3,Int64}}), :(Main.NormalFormGame), :(players)))
  end::Games.NormalFormGame{3,Int64}
```

Is there any way to avoid `Val(N)`?

**Comment by StefanKarpinski** [comment]
> Is there any way to avoid `Val(N)`?

Unfortunately, for the compiler to specialize on different values of `N` this is necessary. However, you could try defining
```jl
cournot(a::Real, c::Real, q_grid::Vector{T}, N::Integer) where {T<:Real} =
    cournot(a, c, q_grid, Val(N))
```
there would be a single outer dynamic dispatch to the appropriate N-specialized version of the `cournot` method. Assuming most of the work is inside of the `cournot` funciton, that would likely be fine and the docs could advice using `Val(N)` in circumstances where the call to `cournot` itself must be fast. I would try that and see how the performance is.

**Comment by oyamad** [comment]
@StefanKarpinski Thanks.
Just to clarify: type inference for `cournot(a::Real, c::Real, q_grid::Vector{T}, N::Integer) where {T<:Real} = cournot(a, c, q_grid, Val(N))` will not work, but it will not be a problem performance wise, as the core function `cournot(a, c, q_grid, Val(N))` should be fast enough?

**Comment by StefanKarpinski** [comment]
What I was saying was that the definition:
```jl
cournot(a::Real, c::Real, q_grid::Vector{T}, N::Integer) where {T<:Real} =
    cournot(a, c, q_grid, Val(N))
```
will involve a dynamic dispatch on `Val{N}` – since `N` is not "in the type domain" so it won't be specialized on for a call that looks like `cournot(a, c, q_grid, 13)`, but that call does slow dynamic dispatch once and then calls `cournot(a, c, q_grid, Val(13))` and once you're *inside* that function call it will be fast and specialized. So... if most of the work is going on inside of `cournot(a, c, q_grid, Val(13))` then you're fine; if `cournot(a, c, q_grid, 13)` is itself in a hot loop, then you'll want to pull the construction of the `Val(13)` further out so that the dispatch is done as far out as possible.

**Comment by oyamad** [comment]
I see, thanks.

**Comment by StefanKarpinski** [comment]
Of course, having both leaves the option in the user's hands.

**Comment by oyamad** [comment]
In the [notebook](http://nbviewer.jupyter.org/github/oyamad/QuantEcon.notebooks/blob/d393c4ae38886f338807fd748bc2f35d20d6cdd4/game_theory_jl.ipynb) I only included the versions with `Val(N)`; see cells `[20]` and `[54]`.

If we include these games in the library, let's reconsider whether we should also provide the versions with just `N` as suggested (with clear documentation).
