### ISSUE TITLE
`outerapproximation` cannot find vertices correctly

### ISSUE THREAD

**Issue by shizejin** [QuantEcon/Games.jl#52]
Hi @cc7768, I was trying to replicate the result of the example demonstrated at the bottom of the notebook [A Recursive Formulation of Repeated Games](https://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/master/recursive_repeated_games.ipynb), but failed:

```@julia
julia> using Games

julia> pd_payoff = [9.0 1.0
                    10.0 3.0]
2×2 Array{Float64,2}:
  9.0  1.0
 10.0  3.0

julia> A = Player(pd_payoff)
2×2 Player{2,Float64}:
  9.0  1.0
 10.0  3.0

julia> B = Player(pd_payoff)
2×2 Player{2,Float64}:
  9.0  1.0
 10.0  3.0

julia> pd = NormalFormGame((A, B))
2×2 NormalFormGame{2,Float64}

julia> rpd1 = RepeatedGame(pd, 0.9)
Games.RepeatedGame{2,Float64}(2×2 NormalFormGame{2,Float64}, 0.9)

julia> hp_pts1 = outerapproximation(rpd1; nH=128, maxiter=750, tol=1e-8);

julia> hp_pts1
7×2 Array{Float64,2}:
 9.63111  4.7454 
 9.0      9.0    
 3.25054  9.85285
 3.0      9.80302
 2.1328   3.95681
 3.0      3.0    
 9.80302  3.0    
```

Plot it out:

<img width="700" alt="2017-09-17 10 28 46" src="https://user-images.githubusercontent.com/22466278/30521258-d98810c0-9bf7-11e7-9006-01878bfbd760.png">

The vertex ` [2.1328,   3.95681]` should not appear here.

I wonder if this is caused by the mistake that would occur when doing transformation between Hrep and Vrep by `polyhedron`. JuliaPolyhedra/Polyhedra.jl#48

**Comment by cc7768** [comment]
Thanks for opening this @shizejin -- That point definitely should not be there.

I will try and have a closer look at this soon and determine whether there might be a bug in computing the hyperplanes or whether it comes from the issue you raised in Polyhedra (thank you @blegat for always being so responsive!).

**Comment by blegat** [comment]
No problem ! It is always helpful to get tricky test cases ;)

**Comment by oyamad** [comment]
@shizejin Has this been resolved?

**Comment by shizejin** [comment]
I believe this problem has been solved by JuliaPolyhedra/Polyhedra.jl#49 and JuliaPolyhedra/Polyhedra.jl#51.
