### ISSUE TITLE
Error from docs/make.jl

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/Games.jl#59]
@shizejin I got the following error by `julia make.jl` (run locally):

```
$ julia make.jl
Documenter: setting up build directory.
ERROR: LoadError: 'lib/base_types_and_methods.md' is not an existing page!
...
```

Can you take a look?

**Comment by shizejin** [comment]
This works well in my computer:

```julia
julia> Pkg.clone("https://github.com/QuantEcon/Games.jl")
INFO: Cloning Games from https://github.com/QuantEcon/Games.jl
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> include("/Users/hyde/.julia/v0.6/Games/docs/make.jl")
Documenter: setting up build directory.
Documenter: expanding markdown templates.
Documenter: building cross-references.
Documenter: running document checks.
 > checking for missing docstrings.
 > running doctests.
 > checking footnote links.
Documenter: populating indices.
Documenter: rendering document.
Documenter: skipping docs deployment.
  You can set DOCUMENTER_DEBUG to "true" in Travis to see more information.
```

Would you mind trying `include("/Users/hyde/.julia/v0.6/Games/docs/auto_doc_gen.jl")` to see if the markdown files can be generated automatically? It should be under the `/Games/docs/src/lib` folder.

Maybe you don't give the permission to write files into the `Games` directory?

**Comment by oyamad** [comment]
Nothing happened: there was no error, and no file was generated.

**Comment by oyamad** [comment]
Ah yes, by running it under `~/.julia`, files were generated. But nothing happens if I do it a clone in another directory.

**Comment by oyamad** [comment]
Can we get html files?

**Comment by shizejin** [comment]
The html files are under `/Games/docs/build`.

I think the problem comes from [this line](https://github.com/QuantEcon/Games.jl/blob/master/docs/auto_doc_gen.jl#L9), I am using the path of the directory in `~/.julia`.

**Comment by oyamad** [comment]
@shizejin Will you write an exact instruction in docs/README.md?

**Comment by shizejin** [comment]
What do you mean by "exact"?

**Comment by oyamad** [comment]
An instruction such that there is no error if I follow it.

**Comment by shizejin** [comment]
I see. I will specify that we can only generate docs under the directory under /.julia (Documenter.jl can only genearate docs for package installed). About HTML files, I think I've stated the location of them. I will try to make them more clear.
Do you see anywhere else that may confuse you when you are trying to generate the docs? (Sorry for the confusion my instruction caused)
