### ISSUE TITLE
Use `QuantEcon.next_k_array!` in `support_enumeration`

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/Games.jl#70]
Implemented by QuantEcon/QuantEcon.jl#199.
(See also QuantEcon/QuantEcon.py#379 for the Python version.)

**Comment by monsij** [comment]
Can anyone help me
Do I need to change the file quantecon/game_theory/support_enumeration.py ? @oyamad

**Comment by oyamad** [comment]
@monsij Thank you for your interest in this issue.

This is Games.jl; you don't have to change any file in QuantEcon.py.

**Comment by oyamad** [comment]
`support_enumeration` is defined in `src/support_enumeration.jl`. The task is to replace `_next_k_array!` and `_next_k_combination` in there with `next_k_array!` and `k_array_rank` from `QuantEcon.jl`.

**Comment by monsij** [comment]
Got it thanks 👍
